# Generated by Django 2.2.7 on 2019-12-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_name', models.CharField(help_text='Enter object name', max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
