# Generated by Django 2.2.7 on 2019-12-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_float', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(help_text='Enter profect name', max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='ObjectList',
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.ProjectList'),
        ),
    ]
