# Generated by Django 2.2.7 on 2019-12-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20191201_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetails',
            old_name='free_float',
            new_name='EF',
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='ES',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='FF',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='LF',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='LS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='TF',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectlist',
            name='man_hour',
            field=models.IntegerField(default=0),
        ),
    ]
