# Generated by Django 2.2.7 on 2019-12-01 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20191201_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='pre_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.ProjectList'),
        ),
    ]
