# Generated by Django 2.2.7 on 2019-12-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_projectlist_pre_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlist',
            name='pre_work',
        ),
        migrations.AddField(
            model_name='projectlist',
            name='pre_work',
            field=models.ManyToManyField(to='firstapp.ProjectList'),
        ),
    ]
