# Generated by Django 2.2.7 on 2019-12-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20191201_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlist',
            name='pre_work',
        ),
        migrations.AddField(
            model_name='projectlist',
            name='pre_work',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
