# Generated by Django 2.2.7 on 2019-12-06 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0006_auto_20191202_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetails',
            name='EF',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='LS',
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectlist',
            name='belong_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='ES',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='FF',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='LF',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='TF',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='project_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='firstapp.ProjectList'),
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='man_hour',
            field=models.FloatField(default=0),
        ),
    ]
